package cit360.hibernate;
// Generated Feb 14, 2017 6:29:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Soda generated by hbm2java
 */
@Entity
@Table(name="soda"
    ,catalog="cit360_hibernate"
)
public class Soda  implements java.io.Serializable {


     private Integer sodaId;
     private String name;
     private String flavor;
     private String color;

    public Soda() {
    }

    public Soda(String name, String flavor, String color) {
       this.name = name;
       this.flavor = flavor;
       this.color = color;
    }

     @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="sodaId", unique=true, nullable=false)
    public Integer getSodaId() {
        return this.sodaId;
    }

    public void setSodaId(Integer sodaId) {
        this.sodaId = sodaId;
    }


    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name="flavor", nullable=false, length=20)
    public String getFlavor() {
        return this.flavor;
    }

    public void setFlavor(String flavor) {
        this.flavor = flavor;
    }


    @Column(name="color", nullable=false, length=20)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }
}


